### ISSUE TITLE
Installation of scportrait with conda on Windows not working

### ISSUE THREAD

**Issue by MarcMarc94** [MannLabs/scPortrait#101]
Following the instructions in the documentation (https://mannlabs.github.io/scPortrait/pages/quickstart/installation.html) including the optional installation of openjdk (Graphtool is not available through conda for Windows) and cloning the git repository, the installation crashes when running pip install -e .   :

output shortened by removing the successful steps at the beginning.

(scportrait) D:\scportrait\scPortrait>pip install -e .
Collecting scikit-fmm (from scportrait==1.0.0)
  Downloading scikit_fmm-2024.9.16.tar.gz (465 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      + meson setup C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4 C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4\.mesonpy-9b3qxjas -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4\.mesonpy-9b3qxjas\meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4
      Build dir: C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4\.mesonpy-9b3qxjas
      Build type: native build
      Project name: skfmm
      Project version: 2024.09.16
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['c++'], ['g++'], ['clang++'], ['clang-cl']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `c++ --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g++ --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang++ --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\bias\AppData\Local\Temp\pip-install-k_icegie\scikit-fmm_4be655a3bc0847cb83cb848d604f03f4\.mesonpy-9b3qxjas\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sophiamaedler** [comment]
scikit-ffm seems to be the cause of this issue and looking at pip the windows build of this package is failing at the moment. There is an already open issue regarding this: https://github.com/scikit-fmm/scikit-fmm/issues/94

As this isn't an issue with scPortrait but one of its dependencies there isn't much we can do at the moment. 

Some suggestions to try and get the install working: 
1. Try installing scPortrait using wsl (https://learn.microsoft.com/en-us/windows/wsl/install). 
2. try installing an older version of scikit-fmm (e.g https://github.com/scikit-fmm/scikit-fmm/releases/tag/2024.05.29) before installing scportrait. If this fixes the issue please report back to us.
